source 'https://github.com/CocoaPods/Specs'

xcodeproj 'OJWTTests'
workspace '../OJWT'
inhibit_all_warnings!

def import_pods
  pod 'OJWT', :path => '../'
end

target :ios do
  platform :ios, '7.1'
  link_with 'iOS Tests'
  import_pods
end

target :osx do
  platform :osx, '10.8'
  link_with 'OS X Tests'
  import_pods
end
